DROP TABLE IF EXISTS SILVER.SILVER_TIME_DIM;

CREATE TABLE SILVER.SILVER_TIME_DIM (
	DATE DATE NOT NULL,
	DAY_OF_MONTH INTEGER,
	DAY_OF_WEEK INTEGER,
	DAY_NAME VARCHAR(9),
	DAY_SHORT_NAME VARCHAR(3),
	IS_WEEKEND BOOLEAN,
	WEEK_OF_MONTH INTEGER,
	WEEK_OF_YEAR INTEGER,
	MONTH INTEGER,
	MONTH_NAME VARCHAR(9),
	MONTH_SHORT_NAME VARCHAR(3),
	QUARTER INTEGER,
	YEAR INTEGER,
	YEAR_MONTH VARCHAR(7),
	YEAR_QUARTER VARCHAR(7),
	MONTH_THIRD VARCHAR(6),
	IS_LEAP_YEAR BOOLEAN,
	DAY_OF_YEAR INTEGER,
	FIRST_DAY_OF_MONTH DATE,
	LAST_DAY_OF_MONTH DATE,
	DAYS_IN_MONTH INTEGER,
	IS_FIRST_DAY_OF_MONTH BOOLEAN,
	IS_LAST_DAY_OF_MONTH BOOLEAN,
	FISCAL_YEAR INTEGER,
	FISCAL_QUARTER INTEGER
);

-- Create index on date column for better join performance
CREATE INDEX IDX_TIME_DIMENSION_DATE ON SILVER.SILVER_TIME_DIM (DATE);
