DROP TABLE IF EXISTS SILVER.SILVER_ACTIVITIES;

CREATE TABLE SILVER.SILVER_ACTIVITIES (
	USERNAME VARCHAR(25),
	DATE DATE,
	ACTIVITY VARCHAR(250),
	ACTIVITY_CREATED_AT TIMESTAMP,
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
