FROM apache/airflow:2.10.0

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        postgresql-client \
        default-jdk \
        libpq-dev \
        gcc \
        python3-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
