DROP TABLE IF EXISTS GOLD.GOLD_BUSIEST_DAYS;

CREATE TABLE GOLD.GOLD_BUSIEST_DAYS (
	DAY_OF_MONTH INTEGER,
	ACTIVITY_COUNT NUMERIC(10, 0),

	YEAR_MONTH VARCHAR(7),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
