DROP TABLE IF EXISTS GOLD.GOLD_DEBT_LEDGER;

CREATE TABLE GOLD.GOLD_DEBT_LEDGER (
	DEBTOR VARCHAR(25),
	CREDITOR VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	NET_BALANCE NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
