DROP TABLE IF EXISTS GOLD.GOLD_EXPENSE_STATS;

CREATE TABLE GOLD.GOLD_EXPENSE_STATS (
	EXPENSE_TYPE VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	MIN_AMOUNT NUMERIC(10, 2),
	AVG_AMOUNT NUMERIC(10, 2),
	MAX_AMOUNT NUMERIC(10, 2),
	NO_OF_ENTRIES NUMERIC(10, 0),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
