DROP TABLE IF EXISTS GOLD.GOLD_USER_ENGAGEMENT;

CREATE TABLE GOLD.GOLD_USER_ENGAGEMENT (
	USERNAME VARCHAR(25),
	WEEK_OF_MONTH INTEGER,
	YEAR INTEGER,
	MONTH INTEGER,
	ACTIVE_DAYS INTEGER,
	ACTIVITY_COUNT INTEGER,
	CREATE_COUNT INTEGER,
	VISIT_COUNT INTEGER,
	MODIFICATION_COUNT INTEGER,
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
