DROP TABLE IF EXISTS GOLD.GOLD_USER_ENTRY_FREQUENCY;

CREATE TABLE GOLD.GOLD_USER_ENTRY_FREQUENCY (
	USERNAME VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	ENTRY_COUNT NUMERIC(10, 0),
	AVG_PRICE NUMERIC(10, 2),
	MEDIAN_PRICE NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
