DROP TABLE IF EXISTS GOLD.GOLD_USER_MONTHLY_SHARE;

CREATE TABLE GOLD.GOLD_USER_MONTHLY_SHARE (
	USERNAME VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	USER_MONTHLY_SPENDING NUMERIC(10, 2),
	MONTHLY_TOTAL_COMBINED NUMERIC(10, 2),
	USER_MONTHLY_SHARE NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
