DROP TABLE IF EXISTS GOLD.GOLD_SPENDING_PER_USER_MONTHLY;

CREATE TABLE GOLD.GOLD_SPENDING_PER_USER_MONTHLY (
	USERNAME VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	TOTAL_SPENDING NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
