DROP TABLE IF EXISTS GOLD.GOLD_USER_ACTIVITIES;

CREATE TABLE GOLD.GOLD_USER_ACTIVITIES (
	USERNAME VARCHAR(25),
	TIME_OF_THE_DAY VARCHAR(15),
	ACTIVITY_COUNT INTEGER,
	CREATE_COUNT INTEGER,
	VISIT_COUNT INTEGER,
	MODIFICATION_COUNT NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
