DROP TABLE IF EXISTS GOLD.GOLD_USER_TRENDS;

CREATE TABLE GOLD.GOLD_USER_TRENDS (
	USERNAME VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	MOM_NET_SPEND_CHANGE NUMERIC(10, 2),
	MOM_NET_CREDITED_CHANGE NUMERIC(10, 2),
	MOM_NET_DEBTED_CHANGE NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
