DROP TABLE IF EXISTS GOLD.GOLD_USER_NET_BALANCES;

CREATE TABLE GOLD.GOLD_USER_NET_BALANCES (
	USERNAME VARCHAR(25),
	YEAR_MONTH VARCHAR(7),
	NET_BALANCE NUMERIC(10, 2),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
