DROP TABLE IF EXISTS GOLD.GOLD_SPENDING_PER_USER_MONTHLY;

CREATE TABLE GOLD.GOLD_SPENDING_PER_USER_MONTHLY (
    username VARCHAR(25),
    month_name VARCHAR(9),
    year INTEGER,
    total_spending NUMERIC(10, 2),
    created_at TIMESTAMPTZ,
    created_by VARCHAR(25)
)
