TRUNCATE TABLE ADMIN.ADMIN_DQ_CHECKS;

INSERT INTO ADMIN.ADMIN_DQ_CHECKS VALUES
(1, 'NULL', TRUE, 'PERFORMS NULL CHECK ON USERNAME', 'SILVER', 'SILVER_USERS', 'USERNAME', FALSE, NULL, NULL),
(2, 'UNIQUE', TRUE, 'PERFORMS UNIQUE CHECK ON USERNAME', 'SILVER', 'SILVER_USERS', 'USERNAME', FALSE, NULL, NULL),
(3, 'DUPLICATE', TRUE, 'PERFORMS DUPLICATE CHECK ON USERNAME', 'SILVER', 'SILVER_USERS', 'USERNAME', FALSE, NULL, NULL),
(4, 'NULL', TRUE, 'PERFORMS NULL CHECK ON USERNAME', 'SILVER', 'SILVER_USERS', 'USERNAME', FALSE, NULL, NULL),
(5, 'NULL', TRUE, 'PERFORMS NULL CHECK ON ADMIN', 'SILVER', 'SILVER_USERS', 'ADMIN', FALSE, NULL, NULL),
(6, 'NULL', TRUE, 'PERFORMS NULL CHECK ON USER_CREATED_AT', 'SILVER', 'SILVER_USERS', 'USER_CREATED_AT', FALSE, NULL, NULL),
(7, 'NULL', TRUE, 'PERFORMS NULL CHECK ON DATE', 'SILVER', 'SILVER_ENTRIES', 'DATE', FALSE, NULL, NULL),
(8, 'NULL', TRUE, 'PERFORMS NULL CHECK ON ITEMS', 'SILVER', 'SILVER_ENTRIES', 'ITEMS', FALSE, NULL, NULL),
(9, 'NULL', TRUE, 'PERFORMS NULL CHECK ON PAID_BY', 'SILVER', 'SILVER_ENTRIES', 'PAID_BY', FALSE, NULL, NULL),
(10, 'NULL', TRUE, 'PERFORMS NULL CHECK ON PRICE', 'SILVER', 'SILVER_ENTRIES', 'PRICE', FALSE, NULL, NULL),
(11, 'NULL', TRUE, 'PERFORMS NULL CHECK ON OWED_BY', 'SILVER', 'SILVER_ENTRIES', 'OWED_BY', FALSE, NULL, NULL),
(12, 'NULL', TRUE, 'PERFORMS NULL CHECK ON ENTRY_CREATED_AT', 'SILVER', 'SILVER_ENTRIES', 'ENTRY_CREATED_AT', FALSE, NULL, NULL),
(13, 'NULL', TRUE, 'PERFORMS NULL CHECK ON ENTRY_CREATED_BY', 'SILVER', 'SILVER_ENTRIES', 'ENTRY_CREATED_BY', FALSE, NULL, NULL),
(14, 'RANGE', TRUE, 'PERFORMS RANGE CHECK ON PRICE', 'SILVER', 'SILVER_ENTRIES', 'PRICE', TRUE, 0, 99999),
(15, 'DUPLICATE', TRUE, 'PERFORMS DUPLICATE CHECK ON DATE, ITEMS, PAID_BY, NOTES, PRICE, ENTRY_UPDATED_AT, OWED_ALL, OWED_BY, PREVIOUS_VERSIONS, ENTRY_CREATED_AT, ENTRY_CREATED_BY, CREATED_AT, CREATED_BY', 'SILVER', 'SILVER_ENTRIES', 'DATE, ITEMS, PAID_BY, NOTES, PRICE, ENTRY_UPDATED_AT, OWED_ALL, OWED_BY, PREVIOUS_VERSIONS, ENTRY_CREATED_AT, ENTRY_CREATED_BY, CREATED_AT, CREATED_BY', FALSE, NULL, NULL),
(16, 'NULL', TRUE, 'PERFORMS NULL CHECK ON USERNAME', 'SILVER', 'SILVER_ACTIVITIES', 'USERNAME', FALSE, NULL, NULL),
(17, 'NULL', TRUE, 'PERFORMS NULL CHECK ON DATE', 'SILVER', 'SILVER_ACTIVITIES', 'DATE', FALSE, NULL, NULL),
(18, 'NULL', TRUE, 'PERFORMS NULL CHECK ON ACTIVITY', 'SILVER', 'SILVER_ACTIVITIES', 'ACTIVITY', FALSE, NULL, NULL),
(19, 'NULL', TRUE, 'PERFORMS NULL CHECK ON ACTIVITY_CREATED_AT', 'SILVER', 'SILVER_ACTIVITIES', 'ACTIVITY_CREATED_AT', FALSE, NULL, NULL);
