\connect hisaab_analytics
CREATE SCHEMA IF NOT EXISTS BRONZE AUTHORIZATION airflow;
CREATE SCHEMA IF NOT EXISTS SILVER AUTHORIZATION airflow;
CREATE SCHEMA IF NOT EXISTS GOLD AUTHORIZATION airflow;
CREATE SCHEMA IF NOT EXISTS ADMIN AUTHORIZATION airflow;
