DROP TABLE IF EXISTS ADMIN.ADMIN_DQ_CHECKS;

CREATE TABLE ADMIN.ADMIN_DQ_CHECKS (
	ID INTEGER,
	TYPE VARCHAR(25),
	ACTIVE BOOLEAN,
	DESCRIPTION VARCHAR(250),
	TARGET_SCHEMA VARCHAR(50),
	TARGET_TABLE VARCHAR(50),
	TARGET_COLUMN VARCHAR(150),
	RANGE_CHECK BOOLEAN,
	LOWER_RANGE NUMERIC(10,2),
	UPPER_RANGE NUMERIC(10,2)
)
