DROP TABLE IF EXISTS BRONZE.BRONZE_ENTRIES;

CREATE TABLE BRONZE.BRONZE_ENTRIES (
	ENTRY_CREATED_AT VARCHAR(25),
	ENTRY_CREATED_BY VARCHAR(25),
	DATE VARCHAR(25),
	ITEMS VARCHAR(100),
	NOTES VARCHAR(250),
	OWED_ALL VARCHAR(25),
	OWED_BY VARCHAR(100),
	PAID_BY VARCHAR(25),
	PREVIOUS_VERSIONS VARCHAR(2500),
	PRICE VARCHAR(25),
	UPDATED_AT VARCHAR(25),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
