DROP TABLE IF EXISTS BRONZE.BRONZE_USERS;

CREATE TABLE BRONZE.BRONZE_USERS (
	ADMIN VARCHAR(5),
	USER_CREATED_AT VARCHAR(25),
	USERNAME VARCHAR(25),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
