DROP TABLE IF EXISTS BRONZE.BRONZE_ACTIVITIES;

CREATE TABLE BRONZE.BRONZE_ACTIVITIES (
	ACTIVITY VARCHAR(250),
	ACTIVITY_CREATED_AT VARCHAR(25),
	DATE VARCHAR(25),
	USERNAME VARCHAR(25),
	CREATED_AT TIMESTAMPTZ,
	CREATED_BY VARCHAR(25)
)
